Rigid Body Dynamics Library: src/Model_formatted.cc File Reference
Model_formatted.cc File Reference
Functions
unsigned int AddBodyFixedJoint (Model &model, const unsigned int parent_id, const SpatialTransform &joint_frame, const Joint &UNUSED(joint), const Body &body, std::string body_name)
unsigned int AddBodyMultiDofJoint (Model &model, const unsigned int parent_id, const SpatialTransform &joint_frame, const Joint &joint, const Body &body, std::string body_name)
Function Documentation
AddBodyFixedJoint()
unsigned int AddBodyFixedJoint (Model & model, const unsigned int parent_id, const SpatialTransform & joint_frame, const Joint & UNUSEDjoint, const Body & body, std::string body_name)
Definition at line 85 of file Model_formatted.cc.
References FixedBody::CreateFromBody(), SpatialRigidBodyInertia::createFromMassComInertiaC(), Model::fixed_body_discriminator, Model::I, Model::IsFixedBodyId(), Body::Join(), Model::mBodies, Model::mBodyNameMap, Body::mCenterOfMass, Model::mFixedBodies, Body::mInertia, Body::mMass, FixedBody::mMovableParent, and FixedBody::mParentTransform.
AddBodyMultiDofJoint()
unsigned int AddBodyMultiDofJoint (Model & model, const unsigned int parent_id, const SpatialTransform & joint_frame, const Joint & joint, const Body & body, std::string body_name)
Definition at line 141 of file Model_formatted.cc.
References Model::AddBody(), Model::AddBodyCustomJoint(), AddBodyFixedJoint(), Model::AppendBody(), SpatialRigidBodyInertia::createFromMassComInertiaC(), Joint::custom_joint_index, RigidBodyDynamics::JointType1DoF, RigidBodyDynamics::JointType2DoF, RigidBodyDynamics::JointType3DoF, RigidBodyDynamics::JointType4DoF, RigidBodyDynamics::JointType5DoF, RigidBodyDynamics::JointType6DoF, RigidBodyDynamics::JointTypeCustom, RigidBodyDynamics::JointTypeEulerXYZ, RigidBodyDynamics::JointTypeEulerYXZ, RigidBodyDynamics::JointTypeEulerZXY, RigidBodyDynamics::JointTypeEulerZYX, RigidBodyDynamics::JointTypeFixed, RigidBodyDynamics::JointTypeFloatingBase, RigidBodyDynamics::JointTypeHelical, RigidBodyDynamics::JointTypePrismatic, RigidBodyDynamics::JointTypeRevolute, RigidBodyDynamics::JointTypeRevoluteX, RigidBodyDynamics::JointTypeRevoluteY, RigidBodyDynamics::JointTypeRevoluteZ, RigidBodyDynamics::JointTypeSpherical, RigidBodyDynamics::JointTypeTranslationXYZ, RigidBodyDynamics::JointTypeUndefined, Body::mCenterOfMass, Joint::mDoFCount, CustomJoint::mDoFCount, Body::mInertia, Body::mIsVirtual, Joint::mJointAxes, Joint::mJointType, and Body::mMass.