Rigid Body Dynamics Library: MX_Xd_static< nrows, ncols > Class Template Reference
MX_Xd_static< nrows, ncols > Class Template Reference
#include <MX_Xd_static.h>
Public Member Functions
MX_Xd_static ()
virtual ~MX_Xd_static ()
MX_Xd_static (const double val)
MX_Xd_static (const casadi::MX &m)
MX_Xd_static (const MX_Xd_scalar &v0, const MX_Xd_scalar &v1)
MX_Xd_static (const MX_Xd_scalar &v0, const MX_Xd_scalar &v1, const MX_Xd_scalar &v2)
MX_Xd_static (const MX_Xd_scalar &v0, const MX_Xd_scalar &v1, const MX_Xd_scalar &v2, const MX_Xd_scalar &v3)
MX_Xd_static (const MX_Xd_scalar &v0, const MX_Xd_scalar &v1, const MX_Xd_scalar &v2, const MX_Xd_scalar &v3, const MX_Xd_scalar &v4, const MX_Xd_scalar &v5)
MX_Xd_static (const MX_Xd_scalar &v0, const MX_Xd_scalar &v1, const MX_Xd_scalar &v2, const MX_Xd_scalar &v3, const MX_Xd_scalar &v4, const MX_Xd_scalar &v5, const MX_Xd_scalar &v6, const MX_Xd_scalar &v7)
MX_Xd_static (const MX_Xd_scalar &v00, const MX_Xd_scalar &v01, const MX_Xd_scalar &v02, const MX_Xd_scalar &v10, const MX_Xd_scalar &v11, const MX_Xd_scalar &v12, const MX_Xd_scalar &v20, const MX_Xd_scalar &v21, const MX_Xd_scalar &v22)
MX_Xd_static (const MX_Xd_scalar &v00, const MX_Xd_scalar &v01, const MX_Xd_scalar &v02, const MX_Xd_scalar &v03, const MX_Xd_scalar &v10, const MX_Xd_scalar &v11, const MX_Xd_scalar &v12, const MX_Xd_scalar &v13, const MX_Xd_scalar &v20, const MX_Xd_scalar &v21, const MX_Xd_scalar &v22, const MX_Xd_scalar &v23, const MX_Xd_scalar &v30, const MX_Xd_scalar &v31, const MX_Xd_scalar &v32, const MX_Xd_scalar &v33)
MX_Xd_static (const MX_Xd_scalar &v00, const MX_Xd_scalar &v01, const MX_Xd_scalar &v02, const MX_Xd_scalar &v03, const MX_Xd_scalar &v04, const MX_Xd_scalar &v05, const MX_Xd_scalar &v10, const MX_Xd_scalar &v11, const MX_Xd_scalar &v12, const MX_Xd_scalar &v13, const MX_Xd_scalar &v14, const MX_Xd_scalar &v15, const MX_Xd_scalar &v20, const MX_Xd_scalar &v21, const MX_Xd_scalar &v22, const MX_Xd_scalar &v23, const MX_Xd_scalar &v24, const MX_Xd_scalar &v25, const MX_Xd_scalar &v30, const MX_Xd_scalar &v31, const MX_Xd_scalar &v32, const MX_Xd_scalar &v33, const MX_Xd_scalar &v34, const MX_Xd_scalar &v35, const MX_Xd_scalar &v40, const MX_Xd_scalar &v41, const MX_Xd_scalar &v42, const MX_Xd_scalar &v43, const MX_Xd_scalar &v44, const MX_Xd_scalar &v45, const MX_Xd_scalar &v50, const MX_Xd_scalar &v51, const MX_Xd_scalar &v52, const MX_Xd_scalar &v53, const MX_Xd_scalar &v54, const MX_Xd_scalar &v55)
void set (const MX_Xd_scalar &v0, const MX_Xd_scalar &v1, const MX_Xd_scalar &v2)
set For 3d Vector
void set (const MX_Xd_scalar &v0, const MX_Xd_scalar &v1, const MX_Xd_scalar &v2, const MX_Xd_scalar &v3)
set For Quaternion
void set (const MX_Xd_scalar &v0, const MX_Xd_scalar &v1, const MX_Xd_scalar &v2, const MX_Xd_scalar &v3, const MX_Xd_scalar &v4, const MX_Xd_scalar &v5)
set For SpatialVector
MX_Xd_static & setIdentity ()
MX_Xd_static & setZero ()
MX_Xd_static & setOnes ()
unsigned int rows () const
unsigned int cols () const
unsigned int size () const
template<unsigned int row_count, unsigned int col_count>
MX_Xd_SubMatrix block (unsigned int row_start, unsigned int col_start)
template<unsigned int row_count, unsigned int col_count>
MX_Xd_static< row_count, col_count > block (unsigned int row_start, unsigned int col_start) const
MX_Xd_SubMatrix block (unsigned int row_start, unsigned int col_start, unsigned int row_count, unsigned int col_count)
MX_Xd_dynamic block (unsigned int row_start, unsigned int col_start, unsigned int row_count, unsigned int col_count) const
MX_Xd_SubMatrix operator[] (unsigned int i)
MX_Xd_SubMatrix operator() (unsigned int i, unsigned int j=0)
MX_Xd_scalar operator[] (unsigned int i) const
MX_Xd_scalar operator() (unsigned int i, unsigned int j=0) const
MX_Xd_scalar dot (const MX_Xd_static< ncols, 1 > &other_vector) const
MX_Xd_static< 3, 1 > cross (const MX_Xd_static< 3, 1 > &other_vector) const
MX_Xd_static< ncols, nrows > transpose () const
MX_Xd_static< ncols, nrows > inverse () const
MX_Xd_scalar norm () const
MX_Xd_scalar squaredNorm () const
void normalize ()
void operator+= (const MX_Xd_static< nrows, ncols > &other)
MX_Xd_static< nrows, ncols > operator+ (const MX_Xd_static< nrows, ncols > &other) const
void operator-= (const MX_Xd_static< nrows, ncols > &other)
MX_Xd_static< nrows, ncols > operator- (const MX_Xd_static< nrows, ncols > &other) const
template<unsigned int ncols2>
void operator*= (const MX_Xd_static< ncols, ncols2 > &m2)
template<unsigned int ncols2>
MX_Xd_static< nrows, ncols2 > operator* (const MX_Xd_static< ncols, ncols2 > &other) const
MX_Xd_static< nrows, ncols > operator* (const MX_Xd_scalar &other) const
void operator*= (const MX_Xd_scalar &other)
void operator/= (const MX_Xd_scalar &scalar)
MX_Xd_static< nrows, ncols > operator/ (const MX_Xd_scalar &scalar) const
MX_Xd_static< nrows, ncols > operator/ (const MX_Xd_SubMatrix &scalar) const
Static Public Member Functions
static MX_Xd_static Identity ()
static MX_Xd_static Zero ()
static MX_Xd_static One ()
Detailed Description
template<unsigned int nrows, unsigned int ncols>
class RBDLCasadiMath::MX_Xd_static< nrows, ncols >
Definition at line 23 of file MX_Xd_static.h.
Constructor & Destructor Documentation
MX_Xd_static() [1/11]
MX_Xd_static () inline
Definition at line 25 of file MX_Xd_static.h.
~MX_Xd_static()
virtual ~MX_Xd_static () inline virtual
Definition at line 29 of file MX_Xd_static.h.
MX_Xd_static() [2/11]
MX_Xd_static (const double val) inline
Definition at line 33 of file MX_Xd_static.h.
MX_Xd_static() [3/11]
MX_Xd_static (const casadi::MX & m) inline
Definition at line 38 of file MX_Xd_static.h.
MX_Xd_static() [4/11]
MX_Xd_static (const MX_Xd_scalar & v0, const MX_Xd_scalar & v1) inline
Definition at line 41 of file MX_Xd_static.h.
MX_Xd_static() [5/11]
MX_Xd_static (const MX_Xd_scalar & v0, const MX_Xd_scalar & v1, const MX_Xd_scalar & v2) inline
Definition at line 49 of file MX_Xd_static.h.
MX_Xd_static() [6/11]
MX_Xd_static (const MX_Xd_scalar & v0, const MX_Xd_scalar & v1, const MX_Xd_scalar & v2, const MX_Xd_scalar & v3) inline
Definition at line 60 of file MX_Xd_static.h.
MX_Xd_static() [7/11]
MX_Xd_static (const MX_Xd_scalar & v0, const MX_Xd_scalar & v1, const MX_Xd_scalar & v2, const MX_Xd_scalar & v3, const MX_Xd_scalar & v4, const MX_Xd_scalar & v5) inline
Definition at line 71 of file MX_Xd_static.h.
MX_Xd_static() [8/11]
MX_Xd_static (const MX_Xd_scalar & v0, const MX_Xd_scalar & v1, const MX_Xd_scalar & v2, const MX_Xd_scalar & v3, const MX_Xd_scalar & v4, const MX_Xd_scalar & v5, const MX_Xd_scalar & v6, const MX_Xd_scalar & v7) inline
Definition at line 87 of file MX_Xd_static.h.
MX_Xd_static() [9/11]
MX_Xd_static (const MX_Xd_scalar & v00, const MX_Xd_scalar & v01, const MX_Xd_scalar & v02, const MX_Xd_scalar & v10, const MX_Xd_scalar & v11, const MX_Xd_scalar & v12, const MX_Xd_scalar & v20, const MX_Xd_scalar & v21, const MX_Xd_scalar & v22) inline
Definition at line 107 of file MX_Xd_static.h.
MX_Xd_static() [10/11]
MX_Xd_static (const MX_Xd_scalar & v00, const MX_Xd_scalar & v01, const MX_Xd_scalar & v02, const MX_Xd_scalar & v03, const MX_Xd_scalar & v10, const MX_Xd_scalar & v11, const MX_Xd_scalar & v12, const MX_Xd_scalar & v13, const MX_Xd_scalar & v20, const MX_Xd_scalar & v21, const MX_Xd_scalar & v22, const MX_Xd_scalar & v23, const MX_Xd_scalar & v30, const MX_Xd_scalar & v31, const MX_Xd_scalar & v32, const MX_Xd_scalar & v33) inline
Definition at line 123 of file MX_Xd_static.h.
MX_Xd_static() [11/11]
MX_Xd_static (const MX_Xd_scalar & v00, const MX_Xd_scalar & v01, const MX_Xd_scalar & v02, const MX_Xd_scalar & v03, const MX_Xd_scalar & v04, const MX_Xd_scalar & v05, const MX_Xd_scalar & v10, const MX_Xd_scalar & v11, const MX_Xd_scalar & v12, const MX_Xd_scalar & v13, const MX_Xd_scalar & v14, const MX_Xd_scalar & v15, const MX_Xd_scalar & v20, const MX_Xd_scalar & v21, const MX_Xd_scalar & v22, const MX_Xd_scalar & v23, const MX_Xd_scalar & v24, const MX_Xd_scalar & v25, const MX_Xd_scalar & v30, const MX_Xd_scalar & v31, const MX_Xd_scalar & v32, const MX_Xd_scalar & v33, const MX_Xd_scalar & v34, const MX_Xd_scalar & v35, const MX_Xd_scalar & v40, const MX_Xd_scalar & v41, const MX_Xd_scalar & v42, const MX_Xd_scalar & v43, const MX_Xd_scalar & v44, const MX_Xd_scalar & v45, const MX_Xd_scalar & v50, const MX_Xd_scalar & v51, const MX_Xd_scalar & v52, const MX_Xd_scalar & v53, const MX_Xd_scalar & v54, const MX_Xd_scalar & v55) inline
Definition at line 147 of file MX_Xd_static.h.
Member Function Documentation
block() [1/4]
MX_Xd_SubMatrix block (unsigned int row_start, unsigned int col_start) inline
Definition at line 291 of file MX_Xd_static.h.
block() [2/4]
MX_Xd_static< row_count, col_count > block (unsigned int row_start, unsigned int col_start) const inline
Definition at line 300 of file MX_Xd_static.h.
block() [3/4]
MX_Xd_SubMatrix block (unsigned int row_start, unsigned int col_start, unsigned int row_count, unsigned int col_count) inline
Definition at line 308 of file MX_Xd_static.h.
block() [4/4]
MX_Xd_dynamic block (unsigned int row_start, unsigned int col_start, unsigned int row_count, unsigned int col_count) const inline
Definition at line 318 of file MX_Xd_static.h.
cols()
unsigned int cols () const inline
Definition at line 282 of file MX_Xd_static.h.
cross()
MX_Xd_static< 3, 1 > cross (const MX_Xd_static< 3, 1 > & other_vector) const inline
Definition at line 349 of file MX_Xd_static.h.
dot()
MX_Xd_scalar dot (const MX_Xd_static< ncols, 1 > & other_vector) const inline
Definition at line 345 of file MX_Xd_static.h.
Identity()
static MX_Xd_static Identity () inline static
Definition at line 253 of file MX_Xd_static.h.
inverse()
MX_Xd_static< ncols, nrows > inverse () const inline
Definition at line 361 of file MX_Xd_static.h.
norm()
MX_Xd_scalar norm () const inline
Definition at line 386 of file MX_Xd_static.h.
normalize()
void normalize () inline
Definition at line 394 of file MX_Xd_static.h.
References MX_Xd_static< nrows, ncols >::norm().
One()
static MX_Xd_static One () inline static
Definition at line 269 of file MX_Xd_static.h.
operator()() [1/2]
MX_Xd_SubMatrix operator() (unsigned int i, unsigned int j = 0) inline
Definition at line 332 of file MX_Xd_static.h.
operator()() [2/2]
MX_Xd_scalar operator() (unsigned int i, unsigned int j = 0) const inline
Definition at line 340 of file MX_Xd_static.h.
operator*() [1/2]
MX_Xd_static< nrows, ncols > operator* (const MX_Xd_scalar & other) const inline
Definition at line 426 of file MX_Xd_static.h.
operator*() [2/2]
MX_Xd_static< nrows, ncols2 > operator* (const MX_Xd_static< ncols, ncols2 > & other) const inline
Definition at line 423 of file MX_Xd_static.h.
operator*=() [1/2]
void operator*= (const MX_Xd_scalar & other) inline
Definition at line 430 of file MX_Xd_static.h.
operator*=() [2/2]
void operator*= (const MX_Xd_static< ncols, ncols2 > & m2) inline
Definition at line 418 of file MX_Xd_static.h.
operator+()
MX_Xd_static< nrows, ncols > operator+ (const MX_Xd_static< nrows, ncols > & other) const inline
Definition at line 403 of file MX_Xd_static.h.
operator+=()
void operator+= (const MX_Xd_static< nrows, ncols > & other) inline
Definition at line 399 of file MX_Xd_static.h.
operator-()
MX_Xd_static< nrows, ncols > operator- (const MX_Xd_static< nrows, ncols > & other) const inline
Definition at line 412 of file MX_Xd_static.h.
operator-=()
void operator-= (const MX_Xd_static< nrows, ncols > & other) inline
Definition at line 408 of file MX_Xd_static.h.
operator/() [1/2]
MX_Xd_static< nrows, ncols > operator/ (const MX_Xd_scalar & scalar) const inline
Definition at line 438 of file MX_Xd_static.h.
operator/() [2/2]
MX_Xd_static< nrows, ncols > operator/ (const MX_Xd_SubMatrix & scalar) const inline
Definition at line 444 of file MX_Xd_static.h.
operator/=()
void operator/= (const MX_Xd_scalar & scalar) inline
Definition at line 435 of file MX_Xd_static.h.
operator[]() [1/2]
MX_Xd_SubMatrix operator[] (unsigned int i) inline
Definition at line 329 of file MX_Xd_static.h.
operator[]() [2/2]
MX_Xd_scalar operator[] (unsigned int i) const inline
Definition at line 337 of file MX_Xd_static.h.
rows()
unsigned int rows () const inline
Definition at line 278 of file MX_Xd_static.h.
set() [1/3]
void set (const MX_Xd_scalar & v0, const MX_Xd_scalar & v1, const MX_Xd_scalar & v2) inline
set For 3d Vector
Parameters
v0 X
v1 Y
v2 Z
Definition at line 204 of file MX_Xd_static.h.
set() [2/3]
void set (const MX_Xd_scalar & v0, const MX_Xd_scalar & v1, const MX_Xd_scalar & v2, const MX_Xd_scalar & v3) inline
set For Quaternion
Parameters
v0 X
v1 Y
v2 Z
v3 W
Definition at line 219 of file MX_Xd_static.h.
set() [3/3]
void set (const MX_Xd_scalar & v0, const MX_Xd_scalar & v1, const MX_Xd_scalar & v2, const MX_Xd_scalar & v3, const MX_Xd_scalar & v4, const MX_Xd_scalar & v5) inline
set For SpatialVector
Parameters
v0
v1
v2
v3
v4
v5
Definition at line 238 of file MX_Xd_static.h.
setIdentity()
MX_Xd_static & setIdentity () inline
Definition at line 256 of file MX_Xd_static.h.
setOnes()
MX_Xd_static & setOnes () inline
Definition at line 272 of file MX_Xd_static.h.
References MX_Xd_static< nrows, ncols >::cols(), and MX_Xd_static< nrows, ncols >::rows().
setZero()
MX_Xd_static & setZero () inline
Definition at line 264 of file MX_Xd_static.h.
References MX_Xd_static< nrows, ncols >::cols(), and MX_Xd_static< nrows, ncols >::rows().
size()
unsigned int size () const inline
Definition at line 286 of file MX_Xd_static.h.
References MX_Xd_static< nrows, ncols >::cols(), and MX_Xd_static< nrows, ncols >::rows().
squaredNorm()
MX_Xd_scalar squaredNorm () const inline
Definition at line 390 of file MX_Xd_static.h.
References MX_Xd_static< nrows, ncols >::norm().
transpose()
MX_Xd_static< ncols, nrows > transpose () const inline
Definition at line 358 of file MX_Xd_static.h.
Zero()
static MX_Xd_static Zero () inline static
Definition at line 261 of file MX_Xd_static.h.
The documentation for this class was generated from the following file:
include/rbdl/CasadiMath/MX_Xd_static.h