Rigid Body Dynamics Library: std Namespace Reference
std Namespace Reference
STL namespace.
Data Structures
class allocator
STL class.
class array
STL class.
class atomic
STL class.
class atomic_ref
STL class.
class auto_ptr
STL class.
class bad_alloc
STL class.
class bad_cast
STL class.
class bad_exception
STL class.
class bad_typeid
STL class.
class basic_fstream
STL class.
class basic_ifstream
STL class.
class basic_ios
STL class.
class basic_iostream
STL class.
class basic_istream
STL class.
class basic_istringstream
STL class.
class basic_ofstream
STL class.
class basic_ostream
STL class.
class basic_ostringstream
STL class.
class basic_string
STL class.
class basic_string_view
STL class.
class basic_stringstream
STL class.
class bitset
STL class.
class complex
STL class.
class deque
STL class.
class domain_error
STL class.
class error_category
STL class.
class error_code
STL class.
class error_condition
STL class.
class exception
STL class.
class forward_list
STL class.
class fstream
STL class.
class ifstream
STL class.
class invalid_argument
STL class.
class ios
STL class.
class ios_base
STL class.
class istream
STL class.
class istringstream
STL class.
class jthread
STL class.
class length_error
STL class.
class list
STL class.
class lock_guard
STL class.
class logic_error
STL class.
class map
STL class.
class multimap
STL class.
class multiset
STL class.
class mutex
STL class.
class ofstream
STL class.
class ostream
STL class.
class ostringstream
STL class.
class out_of_range
STL class.
class overflow_error
STL class.
class priority_queue
STL class.
class queue
STL class.
class range_error
STL class.
class recursive_mutex
STL class.
class recursive_timed_mutex
STL class.
class runtime_error
STL class.
class set
STL class.
class shared_lock
STL class.
class shared_mutex
STL class.
class shared_ptr
STL class.
class shared_timed_mutex
STL class.
class smart_ptr
STL class.
class span
STL class.
class stack
STL class.
class string
STL class.
class string_view
STL class.
class stringstream
STL class.
class system_error
STL class.
class thread
STL class.
class timed_mutex
STL class.
class u16string
STL class.
class u16string_view
STL class.
class u32string
STL class.
class u32string_view
STL class.
class u8string
STL class.
class u8string_view
STL class.
class underflow_error
STL class.
class unique_lock
STL class.
class unique_ptr
STL class.
class unordered_map
STL class.
class unordered_multimap
STL class.
class unordered_multiset
STL class.
class unordered_set
STL class.
class valarray
STL class.
class vector
STL class.
class weak_ptr
STL class.
class wfstream
STL class.
class wifstream
STL class.
class wios
STL class.
class wistream
STL class.
class wistringstream
STL class.
class wofstream
STL class.
class wostream
STL class.
class wostringstream
STL class.
class wstring
STL class.
class wstring_view
STL class.
class wstringstream
STL class.
Functions
MX_Xd_scalar sqrt (const MX_Xd_scalar &x)
MX_Xd_scalar sin (const MX_Xd_scalar &x)
MX_Xd_scalar asin (const MX_Xd_scalar &x)
MX_Xd_scalar cos (const MX_Xd_scalar &x)
MX_Xd_scalar acos (const MX_Xd_scalar &x)
MX_Xd_scalar tan (const MX_Xd_scalar &x)
MX_Xd_scalar atan2 (const MX_Xd_scalar &x, const MX_Xd_scalar &y)
MX_Xd_scalar tanh (const MX_Xd_scalar &x)
bool isnan (const casadi::MX &x)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_dynamic fabs (const MX_Xd_dynamic &m)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_scalar fabs (const MX_Xd_static< nrows, ncols > &m)
MX_Xd_scalar fabs (const MX_Xd_scalar &m)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > pow (const MX_Xd_static< nrows, ncols > &m, int exponent)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > pow (const MX_Xd_static< nrows, ncols > &m, unsigned int exponent)
template<unsigned int nrows, unsigned int ncols>
MX_Xd_static< nrows, ncols > pow (const MX_Xd_static< nrows, ncols > &m, double exponent)
MX_Xd_scalar pow (const MX_Xd_scalar &m, int exponent)
MX_Xd_scalar pow (const MX_Xd_scalar &m, unsigned int exponent)
MX_Xd_scalar pow (const MX_Xd_scalar &m, double exponent)
Detailed Description
STL namespace.
Function Documentation
acos()
MX_Xd_scalar std::acos (const MX_Xd_scalar & x) inline
Definition at line 354 of file MX_Xd_utils.h.
References acos().
asin()
MX_Xd_scalar std::asin (const MX_Xd_scalar & x) inline
Definition at line 348 of file MX_Xd_utils.h.
References asin().
atan2()
MX_Xd_scalar std::atan2 (const MX_Xd_scalar & x, const MX_Xd_scalar & y) inline
Definition at line 360 of file MX_Xd_utils.h.
References atan2().
cos()
MX_Xd_scalar std::cos (const MX_Xd_scalar & x) inline
Definition at line 351 of file MX_Xd_utils.h.
References cos().
fabs() [1/3]
MX_Xd_dynamic std::fabs (const MX_Xd_dynamic & m) inline
Definition at line 371 of file MX_Xd_utils.h.
fabs() [2/3]
MX_Xd_scalar std::fabs (const MX_Xd_scalar & m) inline
Definition at line 378 of file MX_Xd_utils.h.
fabs() [3/3]
MX_Xd_scalar std::fabs (const MX_Xd_static< nrows, ncols > & m) inline
Definition at line 375 of file MX_Xd_utils.h.
isnan()
bool std::isnan (const casadi::MX & x) inline
Definition at line 366 of file MX_Xd_utils.h.
pow() [1/6]
MX_Xd_scalar std::pow (const MX_Xd_scalar & m, double exponent) inline
Definition at line 400 of file MX_Xd_utils.h.
pow() [2/6]
MX_Xd_scalar std::pow (const MX_Xd_scalar & m, int exponent) inline
Definition at line 394 of file MX_Xd_utils.h.
pow() [3/6]
MX_Xd_scalar std::pow (const MX_Xd_scalar & m, unsigned int exponent) inline
Definition at line 397 of file MX_Xd_utils.h.
pow() [4/6]
MX_Xd_static< nrows, ncols > std::pow (const MX_Xd_static< nrows, ncols > & m, double exponent) inline
Definition at line 391 of file MX_Xd_utils.h.
pow() [5/6]
MX_Xd_static< nrows, ncols > std::pow (const MX_Xd_static< nrows, ncols > & m, int exponent) inline
Definition at line 383 of file MX_Xd_utils.h.
pow() [6/6]
MX_Xd_static< nrows, ncols > std::pow (const MX_Xd_static< nrows, ncols > & m, unsigned int exponent) inline
Definition at line 387 of file MX_Xd_utils.h.
sin()
MX_Xd_scalar std::sin (const MX_Xd_scalar & x) inline
Definition at line 345 of file MX_Xd_utils.h.
References sin().
sqrt()
MX_Xd_scalar std::sqrt (const MX_Xd_scalar & x) inline
Definition at line 342 of file MX_Xd_utils.h.
References sqrt().
tan()
MX_Xd_scalar std::tan (const MX_Xd_scalar & x) inline
Definition at line 357 of file MX_Xd_utils.h.
References tan().
tanh()
MX_Xd_scalar std::tanh (const MX_Xd_scalar & x) inline
Definition at line 363 of file MX_Xd_utils.h.
References tanh().