Rigid Body Dynamics Library: MX_Xd_dynamic Class Reference
MX_Xd_dynamic Class Reference
#include <MX_Xd_dynamic.h>
Public Member Functions
MX_Xd_dynamic (unsigned int nrows=1, unsigned int ncols=1)
virtual ~MX_Xd_dynamic ()
MX_Xd_dynamic (const casadi::MX &m)
void conservativeResize (unsigned int nrows, unsigned int ncols=1)
MX_Xd_dynamic & setZero ()
MX_Xd_dynamic & setOnes ()
MX_Xd_dynamic & setIdentity ()
MX_Xd_SubMatrix operator[] (unsigned int i)
MX_Xd_scalar operator[] (unsigned int i) const
MX_Xd_SubMatrix operator() (unsigned int i, unsigned int j=0)
MX_Xd_scalar operator() (unsigned int i, unsigned int j=0) const
void resize (unsigned int newI, unsigned int newJ=1)
unsigned int rows () const
unsigned int cols () const
unsigned int size () const
template<unsigned int row_count, unsigned int col_count>
MX_Xd_SubMatrix block (unsigned int row_start, unsigned int col_start)
template<unsigned int row_count, unsigned int col_count>
MX_Xd_dynamic block (unsigned int row_start, unsigned int col_start) const
MX_Xd_SubMatrix block (unsigned int row_start, unsigned int col_start, unsigned int row_count, unsigned int col_count)
MX_Xd_dynamic block (unsigned int row_start, unsigned int col_start, unsigned int row_count, unsigned int col_count) const
MX_Xd_SubMatrix topRows (unsigned int numberRows)
MX_Xd_dynamic topRows (unsigned int numberRows) const
MX_Xd_dynamic transpose () const
MX_Xd_dynamic inverse () const
MX_Xd_scalar dot (const MX_Xd_dynamic &other_vector) const
MX_Xd_dynamic norm () const
void normalize ()
MX_Xd_dynamic squaredNorm () const
void operator+= (const MX_Xd_dynamic &other)
MX_Xd_dynamic operator+ (const MX_Xd_dynamic &other) const
void operator-= (const MX_Xd_dynamic &other)
MX_Xd_dynamic operator- (const MX_Xd_dynamic &other) const
void operator*= (const MX_Xd_dynamic &m2)
MX_Xd_dynamic operator* (const MX_Xd_dynamic &other) const
MX_Xd_dynamic operator* (const MX_Xd_scalar &other) const
MX_Xd_dynamic operator* (const MX_Xd_SubMatrix &other) const
MX_Xd_dynamic operator* (const double &other) const
void operator/= (const MX_Xd_scalar &scalar)
MX_Xd_dynamic operator/ (const MX_Xd_scalar &scalar) const
MX_Xd_dynamic operator/ (const MX_Xd_SubMatrix &scalar) const
Static Public Member Functions
static MX_Xd_dynamic Zero (unsigned int nrows, unsigned int ncols=1)
static MX_Xd_dynamic One (unsigned int nrows, unsigned int ncols=1)
static MX_Xd_dynamic Identity (unsigned int size, unsigned int ignoredSize=0)
Detailed Description
Definition at line 21 of file MX_Xd_dynamic.h.
Constructor & Destructor Documentation
MX_Xd_dynamic() [1/2]
MX_Xd_dynamic (unsigned int nrows = 1, unsigned int ncols = 1) inline
Definition at line 23 of file MX_Xd_dynamic.h.
~MX_Xd_dynamic()
virtual ~MX_Xd_dynamic () inline virtual
Definition at line 28 of file MX_Xd_dynamic.h.
MX_Xd_dynamic() [2/2]
MX_Xd_dynamic (const casadi::MX & m) inline
Definition at line 33 of file MX_Xd_dynamic.h.
Member Function Documentation
block() [1/4]
MX_Xd_SubMatrix block (unsigned int row_start, unsigned int col_start) inline
Definition at line 108 of file MX_Xd_dynamic.h.
block() [2/4]
MX_Xd_dynamic block (unsigned int row_start, unsigned int col_start) const inline
Definition at line 117 of file MX_Xd_dynamic.h.
block() [3/4]
MX_Xd_SubMatrix block (unsigned int row_start, unsigned int col_start, unsigned int row_count, unsigned int col_count) inline
Definition at line 126 of file MX_Xd_dynamic.h.
block() [4/4]
MX_Xd_dynamic block (unsigned int row_start, unsigned int col_start, unsigned int row_count, unsigned int col_count) const inline
Definition at line 136 of file MX_Xd_dynamic.h.
cols()
unsigned int cols () const inline
Definition at line 99 of file MX_Xd_dynamic.h.
conservativeResize()
void conservativeResize (unsigned int nrows, unsigned int ncols = 1) inline
Definition at line 37 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols(), and MX_Xd_dynamic::rows().
dot()
MX_Xd_scalar dot (const MX_Xd_dynamic & other_vector) const inline
Definition at line 167 of file MX_Xd_dynamic.h.
Identity()
static MX_Xd_dynamic Identity (unsigned int size, unsigned int ignoredSize = 0) inline static
Definition at line 68 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::size().
inverse()
MX_Xd_dynamic inverse () const inline
Definition at line 163 of file MX_Xd_dynamic.h.
norm()
MX_Xd_dynamic norm () const inline
Definition at line 171 of file MX_Xd_dynamic.h.
normalize()
void normalize () inline
Definition at line 175 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::norm().
One()
static MX_Xd_dynamic One (unsigned int nrows, unsigned int ncols = 1) inline static
Definition at line 60 of file MX_Xd_dynamic.h.
operator()() [1/2]
MX_Xd_SubMatrix operator() (unsigned int i, unsigned int j = 0) inline
Definition at line 82 of file MX_Xd_dynamic.h.
operator()() [2/2]
MX_Xd_scalar operator() (unsigned int i, unsigned int j = 0) const inline
Definition at line 87 of file MX_Xd_dynamic.h.
operator*() [1/4]
MX_Xd_dynamic operator* (const double & other) const inline
Definition at line 214 of file MX_Xd_dynamic.h.
operator*() [2/4]
MX_Xd_dynamic operator* (const MX_Xd_dynamic & other) const inline
Definition at line 205 of file MX_Xd_dynamic.h.
operator*() [3/4]
MX_Xd_dynamic operator* (const MX_Xd_scalar & other) const inline
Definition at line 208 of file MX_Xd_dynamic.h.
operator*() [4/4]
MX_Xd_dynamic operator* (const MX_Xd_SubMatrix & other) const inline
Definition at line 211 of file MX_Xd_dynamic.h.
operator*=()
void operator*= (const MX_Xd_dynamic & m2) inline
Definition at line 201 of file MX_Xd_dynamic.h.
operator+()
MX_Xd_dynamic operator+ (const MX_Xd_dynamic & other) const inline
Definition at line 187 of file MX_Xd_dynamic.h.
operator+=()
void operator+= (const MX_Xd_dynamic & other) inline
Definition at line 183 of file MX_Xd_dynamic.h.
operator-()
MX_Xd_dynamic operator- (const MX_Xd_dynamic & other) const inline
Definition at line 196 of file MX_Xd_dynamic.h.
operator-=()
void operator-= (const MX_Xd_dynamic & other) inline
Definition at line 192 of file MX_Xd_dynamic.h.
operator/() [1/2]
MX_Xd_dynamic operator/ (const MX_Xd_scalar & scalar) const inline
Definition at line 222 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols(), and MX_Xd_dynamic::rows().
operator/() [2/2]
MX_Xd_dynamic operator/ (const MX_Xd_SubMatrix & scalar) const inline
Definition at line 231 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols(), and MX_Xd_dynamic::rows().
operator/=()
void operator/= (const MX_Xd_scalar & scalar) inline
Definition at line 218 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols(), and MX_Xd_dynamic::rows().
operator[]() [1/2]
MX_Xd_SubMatrix operator[] (unsigned int i) inline
Definition at line 76 of file MX_Xd_dynamic.h.
operator[]() [2/2]
MX_Xd_scalar operator[] (unsigned int i) const inline
Definition at line 79 of file MX_Xd_dynamic.h.
resize()
void resize (unsigned int newI, unsigned int newJ = 1) inline
Definition at line 91 of file MX_Xd_dynamic.h.
rows()
unsigned int rows () const inline
Definition at line 95 of file MX_Xd_dynamic.h.
setIdentity()
MX_Xd_dynamic & setIdentity () inline
Definition at line 71 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols().
setOnes()
MX_Xd_dynamic & setOnes () inline
Definition at line 63 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols(), and MX_Xd_dynamic::rows().
setZero()
MX_Xd_dynamic & setZero () inline
Definition at line 55 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols(), and MX_Xd_dynamic::rows().
size()
unsigned int size () const inline
Definition at line 103 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols(), and MX_Xd_dynamic::rows().
squaredNorm()
MX_Xd_dynamic squaredNorm () const inline
Definition at line 179 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::norm().
topRows() [1/2]
MX_Xd_SubMatrix topRows (unsigned int numberRows) inline
Definition at line 147 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::cols().
topRows() [2/2]
MX_Xd_dynamic topRows (unsigned int numberRows) const inline
Definition at line 152 of file MX_Xd_dynamic.h.
References MX_Xd_dynamic::block(), and MX_Xd_dynamic::cols().
transpose()
MX_Xd_dynamic transpose () const inline
Definition at line 159 of file MX_Xd_dynamic.h.
Zero()
static MX_Xd_dynamic Zero (unsigned int nrows, unsigned int ncols = 1) inline static
Definition at line 52 of file MX_Xd_dynamic.h.
The documentation for this class was generated from the following file:
include/rbdl/CasadiMath/MX_Xd_dynamic.h